seed: 42
data:
  root: data/raw/uw-madison-gi-tract-image-segmentation
  train_csv: train.csv
  image_size: 384
  slice_window: 5
  crop_mode: none
  valid_fold: 1
  num_folds: 5
  num_workers: 8
  sampling: all_slices
  limit_train_samples: null
  limit_valid_samples: null
  limit_strategy: none
model:
  name: smp_unetplusplus_efficientnet-b3
  encoder_weights: imagenet
  in_channels: 5
  num_classes: 3
  classification_head: true
train:
  epochs: 30
  batch_size: 16
  lr: 0.0002
  min_lr: 1.0e-06
  weight_decay: 1.0e-05
  scheduler: cosine
  gradient_accumulation_steps: 1
  amp: true
  device: auto
  resume_from_checkpoint: null
  early_stopping_patience: 8
  output_dir: outputs/nnunet_route_stage1_2p5d_unetpp_b3_fold1
  ema:
    enabled: true
    decay: 0.999
loss:
  name: dice_bce
  bce_weight: 0.4
  dice_weight: 0.6
  cls_weight: 0.2
inference:
  tta: true
  batch_size: 16
postprocess:
  mask_thresholds:
  - 0.3
  - 0.4
  - 0.3
  cls_thresholds:
  - 0.5
  - 0.5
  - 0.5
  min_area:
  - 24
  - 24
  - 24
