seed: 42
data:
  root: data/raw/uw-madison-gi-tract-image-segmentation
  train_csv: train.csv
  image_size: 384
  valid_fold: 0
  num_folds: 5
  num_workers: 2
model:
  name: smp_unetplusplus_efficientnet-b3
  encoder_weights: imagenet
  in_channels: 1
  num_classes: 3
train:
  epochs: 30
  batch_size: 4
  lr: 0.0002
  weight_decay: 0.00001
  amp: true
  device: auto
  output_dir: outputs/unetplusplus_effb3_full
loss:
  bce_weight: 0.4
  dice_weight: 0.6

