from __future__ import annotations

import argparse
import json
import os
import re
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PYTHON = Path(sys.executable)
RUN_DIR = ROOT / "outputs/next_steps_auto"
LOG_PATH = RUN_DIR / "next_steps_auto.log"
STATUS_PATH = RUN_DIR / "status.json"


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def log(message: str) -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    line = f"[{utc_now()}] {message}"
    print(line, flush=True)
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def read_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def write_yaml(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")


def run_step(name: str, command: list[str], log_file: Path, force: bool = False, expected: Path | None = None) -> str:
    if expected is not None and expected.exists() and not force:
        log(f"{name}: reusing existing artifact {expected}")
        return "reused"
    log(f"{name}: starting")
    log_file.parent.mkdir(parents=True, exist_ok=True)
    with log_file.open("ab") as f:
        f.write(("$ " + " ".join(command) + "\n\n").encode())
        subprocess.run(command, cwd=ROOT, stdout=f, stderr=subprocess.STDOUT, check=True)
    log(f"{name}: finished")
    return "completed"


def output_dir(config_path: Path) -> Path:
    cfg = read_yaml(config_path)
    return ROOT / cfg["train"]["output_dir"]


def checkpoint_for(config_path: Path) -> Path | None:
    out = output_dir(config_path)
    for name in ["best_postprocess.pt", "best.pt"]:
        candidate = out / name
        if candidate.exists():
            return candidate
    return None


def read_pid(path: Path) -> int | None:
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8", errors="ignore").strip()
    return int(text) if text.isdigit() else None


def alive(pid: int | None) -> bool:
    if pid is None:
        return False
    try:
        stat = subprocess.check_output(["ps", "-p", str(pid), "-o", "stat="], text=True).strip()
        if not stat or stat.startswith("Z"):
            return False
    except subprocess.CalledProcessError:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def latest_metric(out_dir: Path) -> str:
    path = out_dir / "train.log"
    if not path.exists():
        return "no train.log"
    text = path.read_bytes().decode("utf-8", "ignore")
    metrics = [line.strip() for line in re.split(r"[\r\n]+", text) if line.strip().startswith("epoch=")]
    return metrics[-1] if metrics else "training epoch in progress"


def make_config(
    base_path: Path,
    target_path: Path,
    output: str,
    model_name: str | None = None,
    slice_window: int | None = None,
    batch_size: int | None = None,
    sampling: str | None = None,
    loss: dict | None = None,
    augmentation: dict | None = None,
) -> Path:
    cfg = read_yaml(base_path)
    cfg["train"]["output_dir"] = output
    cfg["data"]["valid_fold"] = 0
    cfg["data"]["limit_train_samples"] = None
    cfg["data"]["limit_valid_samples"] = None
    cfg["train"]["resume_from_checkpoint"] = None
    cfg["train"]["postprocess_eval"] = {"enabled": True}
    if model_name is not None:
        cfg["model"]["name"] = model_name
    if slice_window is not None:
        cfg["data"]["slice_window"] = slice_window
        cfg["model"]["in_channels"] = slice_window
    if batch_size is not None:
        cfg["train"]["batch_size"] = batch_size
        cfg["inference"]["batch_size"] = batch_size
    if sampling is not None:
        cfg["data"]["sampling"] = sampling
    if augmentation is not None:
        cfg["data"]["augmentation"] = augmentation
    if loss is not None:
        cfg["loss"] = loss
    cfg["metadata_note"] = "Generated by scripts/run_next_steps_auto.py for next-step fold0 model selection."
    write_yaml(target_path, cfg)
    return target_path


def ensure_candidate_configs() -> dict[str, Path]:
    base = ROOT / "configs/h200_maskfix_stage1_strategy_e_folds/h200_maskfix_stage1_strategy_e_fold0.yaml"
    config_dir = ROOT / "configs/next_steps_auto"
    common_aug = {
        "affine_prob": 0.65,
        "rotate_limit": 8.0,
        "scale_limit": 0.10,
        "shift_limit": 0.05,
        "distortion_prob": 0.20,
        "distortion_magnitude": 4.0,
        "gamma_prob": 0.35,
        "gamma_limit": [0.80, 1.25],
        "noise_prob": 0.20,
        "noise_std": 0.02,
        "blur_prob": 0.10,
        "blur_kernel": 3,
        "z_dropout_prob": 0.20,
        "z_dropout_max_channels": 2,
    }
    focal_tversky = {
        "name": "focal_tversky",
        "tversky_weight": 1.0,
        "tversky_alpha": 0.35,
        "tversky_beta": 0.65,
        "focal_tversky_gamma": 0.75,
        "cls_weight": 0.2,
    }
    return {
        "unetpp_b5_fold0": make_config(
            base,
            config_dir / "h200_next_unetpp_b5_fold0.yaml",
            "outputs/h200_next_unetpp_b5_fold0",
            model_name="smp_unetplusplus_efficientnet-b5",
            batch_size=8,
        ),
        "deeplabv3plus_resnet50_fold0": make_config(
            base,
            config_dir / "h200_next_deeplabv3plus_resnet50_fold0.yaml",
            "outputs/h200_next_deeplabv3plus_resnet50_fold0",
            model_name="smp_deeplabv3plus_resnet50",
            batch_size=16,
        ),
        "small_bowel_aware_fold0": make_config(
            base,
            config_dir / "h200_next_small_bowel_aware_fold0.yaml",
            "outputs/h200_next_small_bowel_aware_fold0",
            model_name="smp_unetplusplus_efficientnet-b3",
            batch_size=16,
            sampling="organ_balanced",
            loss=focal_tversky,
            augmentation=common_aug,
        ),
    }


def start_training(name: str, config_path: Path, gpu: str, force: bool) -> None:
    out = output_dir(config_path)
    out.mkdir(parents=True, exist_ok=True)
    pid_path = out / "train.pid"
    if alive(read_pid(pid_path)):
        log(f"{name}: already running pid={read_pid(pid_path)}")
        return
    if checkpoint_for(config_path) is not None and not force:
        log(f"{name}: checkpoint exists; skip start ({checkpoint_for(config_path)})")
        return
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = gpu
    cmd = [str(PYTHON), "-u", "-m", "src.uwgi.train", "--config", str(config_path.relative_to(ROOT))]
    log_file = out / "train.log"
    log(f"{name}: starting on CUDA_VISIBLE_DEVICES={gpu}; config={config_path.relative_to(ROOT)}")
    with log_file.open("ab") as f:
        process = subprocess.Popen(
            cmd,
            cwd=ROOT,
            env=env,
            stdout=f,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
    pid_path.write_text(str(process.pid) + "\n", encoding="utf-8")


def training_state(config_path: Path) -> tuple[str, int | None, Path | None, str]:
    out = output_dir(config_path)
    pid = read_pid(out / "train.pid")
    ckpt = checkpoint_for(config_path)
    is_alive = alive(pid)
    if is_alive:
        state = "running"
    elif ckpt is not None:
        state = "completed"
    elif pid is not None:
        state = "failed_or_stopped_without_checkpoint"
    else:
        state = "stopped_or_not_started"
    return state, pid, ckpt, latest_metric(out)


def monitor_trainings(candidates: dict[str, Path], check_seconds: int) -> None:
    while True:
        all_done = True
        status = {"updated_at": utc_now(), "candidates": {}}
        for name, config_path in candidates.items():
            out = output_dir(config_path)
            state, pid, ckpt, metric = training_state(config_path)
            all_done = all_done and state == "completed"
            status["candidates"][name] = {
                "state": state,
                "pid": pid,
                "checkpoint": None if ckpt is None else str(ckpt.relative_to(ROOT)),
                "latest_metric": metric,
                "log": str((out / "train.log").relative_to(ROOT)),
            }
            log(f"{name}: {state}; pid={pid}; {metric}")
        STATUS_PATH.write_text(json.dumps(status, indent=2), encoding="utf-8")
        if all_done:
            log("all fold0 candidate trainings have checkpoints and are stopped")
            return
        time.sleep(check_seconds)


def run_candidate_queue(candidates: dict[str, Path], gpu_ids: list[str], check_seconds: int, force: bool) -> None:
    queue = [
        "unetpp_b5_fold0",
        "deeplabv3plus_resnet50_fold0",
        "small_bowel_aware_fold0",
    ]
    gpu_by_task: dict[str, str] = {}
    if STATUS_PATH.exists():
        try:
            status = json.loads(STATUS_PATH.read_text(encoding="utf-8"))
            for name, item in status.get("candidates", {}).items():
                gpu = item.get("gpu")
                if name in candidates and gpu is not None:
                    gpu_by_task[name] = str(gpu)
        except json.JSONDecodeError:
            log(f"ignoring unreadable status file: {STATUS_PATH}")
    while True:
        running_gpus = set()
        unknown_running = []
        all_done = True
        status = {"updated_at": utc_now(), "candidates": {}}
        for name, config_path in candidates.items():
            state, pid, ckpt, metric = training_state(config_path)
            if state == "running" and name in gpu_by_task:
                running_gpus.add(gpu_by_task[name])
            elif state == "running":
                unknown_running.append(name)
            all_done = all_done and state == "completed"
            status["candidates"][name] = {
                "state": state,
                "pid": pid,
                "gpu": gpu_by_task.get(name),
                "checkpoint": None if ckpt is None else str(ckpt.relative_to(ROOT)),
                "latest_metric": metric,
                "log": str((output_dir(config_path) / "train.log").relative_to(ROOT)),
            }
            log(f"{name}: {state}; gpu={gpu_by_task.get(name)}; pid={pid}; {metric}")
        STATUS_PATH.write_text(json.dumps(status, indent=2), encoding="utf-8")
        if all_done:
            log("all fold0 candidate trainings have checkpoints and are stopped")
            return

        if unknown_running:
            log(
                "running candidates without persisted GPU assignment; "
                f"not launching new jobs until they stop: {', '.join(unknown_running)}"
            )
            time.sleep(check_seconds)
            continue

        free_gpus = [gpu for gpu in gpu_ids if gpu not in running_gpus]
        for name in queue:
            if not free_gpus:
                break
            config_path = candidates[name]
            state, _, _, _ = training_state(config_path)
            if state == "stopped_or_not_started":
                gpu = free_gpus.pop(0)
                gpu_by_task[name] = gpu
                start_training(name, config_path, gpu, force=force)
                time.sleep(5)

        time.sleep(check_seconds)


def checkpoint_name(config_path: Path) -> str:
    out = output_dir(config_path)
    if (out / "best_postprocess.pt").exists():
        return "best_postprocess.pt"
    if (out / "best.pt").exists():
        return "best.pt"
    raise FileNotFoundError(f"No best checkpoint found under {out}")


def evaluate_candidates(candidates: dict[str, Path], force: bool) -> None:
    comparison = []
    for name, config_path in candidates.items():
        out_json = RUN_DIR / f"{name}_official_oof_proxy.json"
        run_step(
            f"eval_{name}",
            [
                str(PYTHON),
                "scripts/evaluate_official_oof.py",
                "--fold-config-glob",
                str(config_path.relative_to(ROOT)),
                "--checkpoint-name",
                checkpoint_name(config_path),
                "--out",
                str(out_json.relative_to(ROOT)),
            ],
            RUN_DIR / f"eval_{name}.log",
            force=force,
            expected=out_json,
        )
        data = json.loads(out_json.read_text(encoding="utf-8"))
        summary = data["summary"]
        small_bowel = summary["classes"]["small_bowel"]
        comparison.append(
            {
                "name": name,
                "config": str(config_path.relative_to(ROOT)),
                "checkpoint": checkpoint_name(config_path),
                "mean_combined_proxy": summary["mean_combined_proxy"],
                "mean_dice_3d": summary["mean_dice_3d"],
                "mean_hd95_mm": summary["mean_hd95_mm"],
                "small_bowel_combined_proxy": small_bowel["mean_combined_proxy"],
                "small_bowel_dice_3d": small_bowel["mean_dice_3d"],
                "small_bowel_hd95_mm": small_bowel["mean_hd95_mm"],
            }
        )

    comparison = sorted(comparison, key=lambda row: row["mean_combined_proxy"], reverse=True)
    (RUN_DIR / "candidate_comparison.json").write_text(json.dumps(comparison, indent=2), encoding="utf-8")
    lines = [
        "# Fold0 Candidate Comparison",
        "",
        "| Rank | Candidate | Combined | Dice 3D | HD95 mm | Small bowel combined | Small bowel Dice | Small bowel HD95 mm |",
        "| ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for idx, row in enumerate(comparison, start=1):
        lines.append(
            f"| {idx} | {row['name']} | {row['mean_combined_proxy']:.5f} | "
            f"{row['mean_dice_3d']:.5f} | {row['mean_hd95_mm']:.2f} | "
            f"{row['small_bowel_combined_proxy']:.5f} | {row['small_bowel_dice_3d']:.5f} | "
            f"{row['small_bowel_hd95_mm']:.2f} |"
        )
    (RUN_DIR / "candidate_comparison.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"candidate comparison saved: {(RUN_DIR / 'candidate_comparison.md').relative_to(ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gpus", default="0,1", help="Comma-separated visible GPU ids used for fold0 candidates.")
    parser.add_argument("--check-seconds", type=int, default=180)
    parser.add_argument("--force-eval", action="store_true")
    parser.add_argument("--force-train", action="store_true")
    parser.add_argument("--skip-train", action="store_true")
    args = parser.parse_args()

    signal.signal(signal.SIGHUP, signal.SIG_IGN)
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    log("next-steps automation started")

    official_eval = RUN_DIR / "maskfix_strategy_e_official_oof_proxy.json"
    run_step(
        "task1_current_official_oof_proxy",
        [
            str(PYTHON),
            "scripts/evaluate_official_oof.py",
            "--fold-config-glob",
            "configs/h200_maskfix_stage1_strategy_e_folds/h200_maskfix_stage1_strategy_e_fold*.yaml",
            "--checkpoint-name",
            "best_postprocess.pt",
            "--out",
            str(official_eval.relative_to(ROOT)),
        ],
        RUN_DIR / "task1_official_eval.log",
        force=args.force_eval,
        expected=official_eval,
    )

    run_step(
        "task2_small_bowel_worst_cases",
        [
            str(PYTHON),
            "scripts/small_bowel_worst_cases.py",
            "--official-eval",
            str(official_eval.relative_to(ROOT)),
            "--out-csv",
            "outputs/next_steps_auto/small_bowel_worst_cases.csv",
            "--out-md",
            "outputs/next_steps_auto/small_bowel_worst_cases.md",
            "--limit",
            "50",
        ],
        RUN_DIR / "task2_small_bowel_worst_cases.log",
        force=True,
        expected=RUN_DIR / "small_bowel_worst_cases.md",
    )

    candidates = ensure_candidate_configs()
    log("task3 candidate configs ready: " + ", ".join(f"{k}={v.relative_to(ROOT)}" for k, v in candidates.items()))
    if args.skip_train:
        log("skip-train requested; not starting fold0 candidates")
        return

    gpu_ids = [gpu.strip() for gpu in args.gpus.split(",") if gpu.strip()]
    if not gpu_ids:
        gpu_ids = ["0"]
    run_candidate_queue(candidates, gpu_ids, args.check_seconds, force=args.force_train)
    evaluate_candidates(candidates, force=args.force_eval)
    log("task4/5 fold0 candidate trainings and candidate official proxy evals finished")
    log("next-steps automation complete")


if __name__ == "__main__":
    main()
